export const readModel = {
    "diagnosisCategorySelectOptions": [
        "Accurately Captured", 
        "Misdiagnosed", 
        "Omitted"
    ], 
    "groups": {
        "Bariatrics": {
            "selectOptions": {
                "conditions": [
                    "Not applicable", 
                    "Acute blood loss anemia", 
                    "Hyponatremia", 
                    "Hypernatremia", 
                    "Chronic kidney disease stage 3", 
                    "Chronic kidney disease stage 4", 
                    "Chronic kidney disease stage 5", 
                    "Encephalopathy due to [specific cause]", 
                    "Drug dependence continuous use", 
                    "Chronic respiratory failure", 
                    "Major depressive disorder [single episode or recurrent episode]", 
                    "Systemic inflammatory response syndrome (SIRS) due to [specific cause]"
                ], 
                "hospitals": [
                    "Harrison", 
                    "Highline", 
                    "St. Anthony", 
                    "St. Clare", 
                    "St. Elizabeth", 
                    "St. Francis", 
                    "St. Joseph"
                ], 
                "providers": [
                    "Dr. David Swedler", 
                    "Elaine Kiser-Rude, PA-C", 
                    "Elizabeth Tobin, PA-C", 
                    "Dr. Haroon Anwar", 
                    "Jennifer Moore, PA-C", 
                    "Kimberly Smits, ARNP", 
                    "Dr. Troy Houseworth"
                ]
            }
        }, 
        "General Surgery": {
            "selectOptions": {
                "conditions": [
                    "Not applicable", 
                    "Acute blood loss anemia", 
                    "Acute diastolic heart failure", 
                    "Chronic diastolic heart failure", 
                    "Acute systolic heart failure", 
                    "Chronic systolic heart failure", 
                    "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                    "Hyponatremia", 
                    "Hypernatremia", 
                    "Chronic kidney disease stage 3", 
                    "Chronic kidney disease stage 4", 
                    "Chronic kidney disease stage 5", 
                    "Encephalopathy due to [specific cause]", 
                    "Morbid obesity exact BMI", 
                    "Severe protein-calorie malnutrition exact BMI", 
                    "Sepsis", 
                    "Severe sepsis", 
                    "Septic shock", 
                    "Acute kidney injury"
                ], 
                "hospitals": [
                    "Harrison", 
                    "Highline", 
                    "St. Anthony", 
                    "St. Clare", 
                    "St. Elizabeth", 
                    "St. Francis", 
                    "St. Joseph"
                ], 
                "providers": [
                    "Dr. Stephen Atkinson", 
                    "Dr. Cathy Baker", 
                    "Dr. Samuel Cargill", 
                    "Dr. Eugene Cho", 
                    "Dr. Steven Duras", 
                    "Dr. Michele Haslinger", 
                    "Dr. Deepali Jain", 
                    "Dr. Mark Nyreen", 
                    "Dr. Linda Pai", 
                    "Dr. Sam Salama", 
                    "Dr. David Swedler", 
                    "Dr. Brian Welch", 
                    "Dr. James Yamashita"
                ]
            }
        }, 
        "Hospitalist": {
            "selectOptions": {
                "conditions": [
                    "Not applicable", 
                    "Acute blood loss anemia", 
                    "Acute diastolic heart failure", 
                    "Chronic diastolic heart failure", 
                    "Acute systolic heart failure", 
                    "Chronic systolic heart failure", 
                    "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                    "Chronic respiratory failure [specify with hypoxia and/or hypercapnia]", 
                    "Hyponatremia", 
                    "Hypernatremia", 
                    "Acute renal failure", 
                    "Chronic kidney disease stage 3", 
                    "Chronic kidney disease stage 4", 
                    "Chronic kidney disease stage 5", 
                    "Encephalopathy due to [specific cause]", 
                    "Morbid obesity exact BMI", 
                    "Protein calorie malnutrition exact BMI", 
                    "Severe protein-calorie malnutrition exact BMI", 
                    "Sepsis", 
                    "Severe sepsis", 
                    "Septic shock", 
                    "Acute renal failure with tubular necrosis", 
                    "Drug [specify type of drug] dependence [specify uncomplicated or with withdrawal]", 
                    "Portal hypertension", 
                    "Chronic respiratory failure"
                ], 
                "hospitals": [
                    "Harrison", 
                    "Highline", 
                    "St. Anthony", 
                    "St. Clare", 
                    "St. Elizabeth", 
                    "St. Francis", 
                    "St. Joseph"
                ], 
                "providers": [
                    "Dr. Ossama Al Masalmeh", 
                    "Dr. Jonathan Bodine", 
                    "Dr. Bhavim Desai", 
                    "Dr. Mehmet Guzelbeyoglu", 
                    "Dr. Christopher Lucas", 
                    "Dr. Carlo Palarca", 
                    "Dr. Saman Selahi", 
                    "Deiter (Mike) Kaizer, PA-C", 
                    "Dr. Eller Manlapaz", 
                    "Dr. Keith Pasternak", 
                    "Dr. Stephen Sim", 
                    "Dr. Yancey Sloane", 
                    "Dr. Ali Thomas", 
                    "Dr. Rebecca Townsend", 
                    "Dr. Zin Tun", 
                    "Dr. Andriy Viter", 
                    "Dr. Rending Xu", 
                    "Dr. Sharooz Zandnia", 
                    "Dr. Mona Shawky", 
                    "Dr. Gurdev Singh", 
                    "Dr. Venkata Yearva", 
                    "Ardith Conway, ARNP", 
                    "Celina Georgia, ARNP", 
                    "Dr. Rosita Hermann", 
                    "Braden Andersen, ARNP", 
                    "Luc Bouquet, ARNP", 
                    "Cherryl Menapace, ARNP", 
                    "Dr. Bhupinder Walia", 
                    "Laurie Benton, ARNP", 
                    "Teresa Harding, ARNP", 
                    "Dr. Andy Nguyen", 
                    "Dr. Syed Abbas", 
                    "Unknown", 
                    "Dr. Fizzah Ali", 
                    "Dr. Viorel Angheloiu", 
                    "Dr. Jennifer Aquino", 
                    "Dr. Amir Aref", 
                    "Dr. Berhane Asfaw", 
                    "Dr. Khalid Aslam", 
                    "Dr. Joseph Barthelemy", 
                    "Dr. Ramon Basa", 
                    "Dr. Kimberly Bell", 
                    "Sharon Bennett, PA-C", 
                    "Dr. Bhavana Bhanot", 
                    "Dr. Himanshu Bhutani", 
                    "Hana Cha, PA-C", 
                    "Dr. Jinsoo Chang", 
                    "Unknown", 
                    "Dr. Sriranjini Chilkunda Ramaswamy", 
                    "Dr. Ishmael Ching", 
                    "Georgia Coote, ARNP", 
                    "Chelsea Crosby, PA-C", 
                    "Dr. Marco Cruz", 
                    "Randal Cupp, PA-C", 
                    "Dr. Lakshmi Datla", 
                    "Dr. Amit Desai", 
                    "Dr. Harjeet Dhillon", 
                    "Dr. Vladimir Dzhashi", 
                    "Dr. Guoping Feng", 
                    "William Finnerty, ARNP", 
                    "Dr. Radu Florea", 
                    "Philip Furth, PA-C", 
                    "Dr. Michal Galeziok", 
                    "Dr. Emad Girgis", 
                    "Dr. Anjna Grover", 
                    "Dr. Matthew Guindon", 
                    "Mary Harris-Tucker, PA-C", 
                    "Mary Harvey, ARNP", 
                    "Dr. Edward Himes", 
                    "Dr. Mai Vi Hoang", 
                    "Unknown", 
                    "Dr. Ihab Ibrahim", 
                    "Dr. Mohamed Imam", 
                    "Lenora Ivanek, PA-C", 
                    "Dr. Nadeem Jaffer", 
                    "Dr. Tonia Jenson", 
                    "Dr. Mark (Jihua) Jia", 
                    "Dr. Audry Kahlstrom", 
                    "Dr. Muhammed Khan", 
                    "Dr. Shadi Khir", 
                    "Unknown", 
                    "Dr. Nikolay Kolev", 
                    "Unknown", 
                    "Dr. Samakshi Krishna", 
                    "Cora Krouse, PA-C", 
                    "Dr. Lakeysha Layfield", 
                    "Dr. David Lee", 
                    "Dr. Desire Lehmann", 
                    "Dr. Michael - PAC L'Italien", 
                    "Dr. Ying Liu", 
                    "Dr. Ed Lopez", 
                    "Laura Luu, ARNP", 
                    "Andrea Lyon-Loftus, PA-C", 
                    "Dr. Naushaba Marri", 
                    "Dr. Liana Maxa", 
                    "Matthew Metsker, PA-C", 
                    "Mihee Montstream, ARNP", 
                    "Albert Morriss, PA-C", 
                    "Unknown", 
                    "Dr. David Munoz", 
                    "Dr. Thankam Nair", 
                    "Michelle Nelson, PA-C", 
                    "Dr. Vivian Nkwonta", 
                    "Dr. Emmy Oh", 
                    "Dr. Srivatsan Padmanabhan", 
                    "Unknown", 
                    "Dr. Ankit Patel", 
                    "Dr. Jay Patel", 
                    "Dr. Seetharam Pothi Reddy", 
                    "Dr. Jeffrey Reasol", 
                    "Dr. Gari Reddy", 
                    "Dr. Prathima Reddy", 
                    "Dr. Azra Rehman", 
                    "Luke Requa, PA-C", 
                    "Dr. David Rochelin", 
                    "Dr. Nirmalya Roychowdhury", 
                    "Dr. Evelyn Rubin", 
                    "Dr. Yasser Said", 
                    "Dr. Vincent Salvador", 
                    "Dr. Shelly Sanetti", 
                    "Dr. Maggie Sekeramayi", 
                    "Dr. Dipam Shah", 
                    "Dr. Megha Shah", 
                    "Dr. Ashwin Shivakumar", 
                    "Dr. Sherrod Shiveley", 
                    "Unknown", 
                    "Dr. Arthur Siek", 
                    "Dr. John Stam", 
                    "Dr. Jessica Tam", 
                    "Dr. Bob Thong", 
                    "Dr. Arinder Tiwana", 
                    "Dr. Tamas Ungar", 
                    "Dr. Nicolas Veohongs", 
                    "Unknown", 
                    "Dr. Pragathy Vutla", 
                    "Dr. John Wagoner", 
                    "Dr. Danhua Wallace", 
                    "Dr. Alison Wright", 
                    "Dr. Gayatri Yambem", 
                    "Dr. Nathaniel Yu Chua", 
                    "Dr. Vitaliy Zak", 
                    "Dr. Wen Zhong", 
                    "Dr. Irina Case", 
                    "Dr. Kelly Carlisle", 
                    "Dr. Mohamed Elagnaf", 
                    "Dr. Zachary Kane", 
                    "Dr. Omar Naji", 
                    "Dr. Phillip Nielson", 
                    "Dr. Rakshit Patnana", 
                    "Dr. Michelle Pham", 
                    "Dr. Jason Chung", 
                    "Dr. Amar Khunti", 
                    "Dr. Sungmi Lian", 
                    "Dr. Dolkar Sherpa", 
                    "Dr. Maninderjit Singh", 
                    "Dr. Chris Stadtherr", 
                    "Dr. Rana Tan", 
                    "Dr. Roberta Trandev", 
                    "Dr. Prabin Uprety", 
                    "Dr. Ashley Hamilton", 
                    "Dr. Timothy Jenkins", 
                    "Dr. Priyanka Kapoor", 
                    "Dr. Ali Alhusseni", 
                    "Dr. Pushpanjali Basnyat", 
                    "Dr. Megha Bendre", 
                    "Dr. Shaluk Biswas", 
                    "Dr. Judy Emil Dela Cruz", 
                    "Dr. Dhananjay Deo", 
                    "Dr. Tianhai (Tim) Guo", 
                    "Dr. Dana Ionescu", 
                    "Dr. Priya Kanwar", 
                    "Dr. Kelly Liu", 
                    "Janet MacKay, RN", 
                    "Dr. Aimee Shariat", 
                    "Dr. Maryam Tariq", 
                    "Kelly Taylor", 
                    "Dr. Thomson Tuscano", 
                    "Dr. Dong Vo"
                ]
            }
        }, 
        "Neurosurgery": {
            "selectOptions": {
                "conditions": [
                    "Not applicable", 
                    "Acute blood loss anemia", 
                    "Hyponatremia", 
                    "Hypernatremia", 
                    "Chronic kidney disease stage 3", 
                    "Chronic kidney disease stage 4", 
                    "Chronic kidney disease stage 5", 
                    "Encephalopathy due to [specific cause]", 
                    "Acute respiratory failure [with hypoxia and/or hypercapnia]", 
                    "Acute kidney injury", 
                    "Cerebral edema", 
                    "Coma GCS score time of record", 
                    "Compression of brain", 
                    "Drug dependence continuous use", 
                    "Hemiparesis [side dominance]", 
                    "Hemiplegia [side dominance]", 
                    "Myelopathy [vascular or nonvascular]"
                ], 
                "hospitals": [
                    "Harrison", 
                    "Highline", 
                    "St. Anthony", 
                    "St. Clare", 
                    "St. Elizabeth", 
                    "St. Francis", 
                    "St. Joseph"
                ], 
                "providers": [
                    "Kelly Andersson, PA-C", 
                    "Dr. Marc Goldman", 
                    "Yelena Golub, PA-C", 
                    "Vladimir V. Grib, ARNP", 
                    "Anastasia Heins, PA-C", 
                    "Caoilin Hoctor, PA-C", 
                    "Catherine Ignacio, ARNP", 
                    "Steven Johns, PA-C", 
                    "Dr. Alex Mohit", 
                    "Dr. Daniel Nehls", 
                    "Dr. Michael Schlitt", 
                    "Dr. Hoan Tran"
                ]
            }
        }, 
        "Vascular": {
            "selectOptions": {
                "conditions": [
                    "Not applicable", 
                    "Acute blood loss anemia", 
                    "Acute diastolic heart failure", 
                    "Chronic diastolic heart failure", 
                    "Acute systolic heart failure", 
                    "Chronic systolic heart failure", 
                    "Hyponatremia", 
                    "Hypernatremia", 
                    "Chronic kidney disease stage 3", 
                    "Chronic kidney disease stage 4", 
                    "Chronic kidney disease stage 5", 
                    "Encephalopathy due to [specific cause]", 
                    "Morbid obesity exact BMI", 
                    "Severe protein-calorie malnutrition exact BMI", 
                    "Septic shock", 
                    "Acute respiratory failure [with hypoxia and/or hypercapnia]", 
                    "Drug dependence continuous use"
                ], 
                "hospitals": [
                    "Harrison", 
                    "Highline", 
                    "St. Anthony", 
                    "St. Clare", 
                    "St. Elizabeth", 
                    "St. Francis", 
                    "St. Joseph"
                ], 
                "providers": [
                    "Jennifer Barnett, ARNP", 
                    "Pamela Charboneau, ARNP", 
                    "Alexandra Engstrom, PA-C", 
                    "Elaine Kiser-Rude, PA-C.", 
                    "Jennifer Moore, PA-C", 
                    "Rachel Sammis-Falk, PA-C", 
                    "Teri Scott, ARNP", 
                    "Anna Singur, PA-C", 
                    "Shawn Tedford, PA-C"
                ]
            }
        }
    }
}