export const readModel = {
    "CHI": {
        "diagnosisCategorySelectOptions": [
            "Accurately Captured", 
            "Misdiagnosed", 
            "Omitted"
        ], 
        "groups": {
            "Bariatrics": {
                "selectOptions": {
                    "conditions": [
                        "Not applicable", 
                        "Acute blood loss anemia", 
                        "Hyponatremia", 
                        "Hypernatremia", 
                        "Chronic kidney disease stage 3", 
                        "Chronic kidney disease stage 4", 
                        "Chronic kidney disease stage 5", 
                        "Encephalopathy due to [specific cause]", 
                        "Drug dependence continuous use", 
                        "Chronic respiratory failure", 
                        "Major depressive disorder [single episode or recurrent episode]", 
                        "Systemic inflammatory response syndrome (SIRS) due to [specific cause]"
                    ], 
                    "hospitals": [
                        "Harrison", 
                        "Highline", 
                        "St. Anthony", 
                        "St. Clare", 
                        "St. Elizabeth", 
                        "St. Francis", 
                        "St. Joseph"
                    ], 
                    "providers": [
                        "Dr. David Swedler", 
                        "Elaine Kiser-Rude, PA-C", 
                        "Elizabeth Tobin, PA-C", 
                        "Dr. Haroon Anwar", 
                        "Jennifer Moore, PA-C", 
                        "Kimberly Smits, ARNP", 
                        "Dr. Troy Houseworth"
                    ]
                }
            }, 
            "General Surgery": {
                "selectOptions": {
                    "conditions": [
                        "Not applicable", 
                        "Acute blood loss anemia", 
                        "Acute diastolic heart failure", 
                        "Chronic diastolic heart failure", 
                        "Acute systolic heart failure", 
                        "Chronic systolic heart failure", 
                        "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Hyponatremia", 
                        "Hypernatremia", 
                        "Chronic kidney disease stage 3", 
                        "Chronic kidney disease stage 4", 
                        "Chronic kidney disease stage 5", 
                        "Encephalopathy due to [specific cause]", 
                        "Morbid obesity exact BMI", 
                        "Severe protein-calorie malnutrition exact BMI", 
                        "Sepsis", 
                        "Severe sepsis", 
                        "Septic shock", 
                        "Acute kidney injury"
                    ], 
                    "hospitals": [
                        "Harrison", 
                        "Highline", 
                        "St. Anthony", 
                        "St. Clare", 
                        "St. Elizabeth", 
                        "St. Francis", 
                        "St. Joseph"
                    ], 
                    "providers": [
                        "Dr. Stephen Atkinson", 
                        "Dr. Cathy Baker", 
                        "Dr. Samuel Cargill", 
                        "Dr. Eugene Cho", 
                        "Dr. Steven Duras", 
                        "Dr. Michele Haslinger", 
                        "Dr. Deepali Jain", 
                        "Dr. Mark Nyreen", 
                        "Dr. Linda Pai", 
                        "Dr. Sam Salama", 
                        "Dr. David Swedler", 
                        "Dr. Brian Welch", 
                        "Dr. James Yamashita"
                    ]
                }
            }, 
            "Hospitalist": {
                "selectOptions": {
                    "conditions": [
                        "Not applicable", 
                        "Acute blood loss anemia", 
                        "Acute diastolic heart failure", 
                        "Chronic diastolic heart failure", 
                        "Acute systolic heart failure", 
                        "Chronic systolic heart failure", 
                        "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Chronic respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Hyponatremia", 
                        "Hypernatremia", 
                        "Acute renal failure", 
                        "Chronic kidney disease stage 3", 
                        "Chronic kidney disease stage 4", 
                        "Chronic kidney disease stage 5", 
                        "Encephalopathy due to [specific cause]", 
                        "Morbid obesity exact BMI", 
                        "Protein calorie malnutrition exact BMI", 
                        "Severe protein-calorie malnutrition exact BMI", 
                        "Sepsis", 
                        "Severe sepsis", 
                        "Septic shock", 
                        "Acute renal failure with tubular necrosis", 
                        "Drug [specify type of drug] dependence [specify uncomplicated or with withdrawal]", 
                        "Portal hypertension", 
                        "Chronic respiratory failure"
                    ], 
                    "hospitals": [
                        "Harrison", 
                        "Highline", 
                        "St. Anthony", 
                        "St. Clare", 
                        "St. Elizabeth", 
                        "St. Francis", 
                        "St. Joseph"
                    ], 
                    "providers": [
                        "Dr. Ossama Al Masalmeh", 
                        "Dr. Jonathan Bodine", 
                        "Dr. Bhavim Desai", 
                        "Dr. Mehmet Guzelbeyoglu", 
                        "Dr. Christopher Lucas", 
                        "Dr. Carlo Palarca", 
                        "Dr. Saman Selahi", 
                        "Deiter (Mike) Kaizer, PA-C", 
                        "Dr. Eller Manlapaz", 
                        "Dr. Keith Pasternak", 
                        "Dr. Stephen Sim", 
                        "Dr. Yancey Sloane", 
                        "Dr. Ali Thomas", 
                        "Dr. Rebecca Townsend", 
                        "Dr. Zin Tun", 
                        "Dr. Andriy Viter", 
                        "Dr. Rending Xu", 
                        "Dr. Sharooz Zandnia", 
                        "Dr. Mona Shawky", 
                        "Dr. Gurdev Singh", 
                        "Dr. Venkata Yearva", 
                        "Ardith Conway, ARNP", 
                        "Celina Georgia, ARNP", 
                        "Dr. Rosita Hermann", 
                        "Braden Andersen, ARNP", 
                        "Luc Bouquet, ARNP", 
                        "Cherryl Menapace, ARNP", 
                        "Dr. Bhupinder Walia", 
                        "Laurie Benton, ARNP", 
                        "Teresa Harding, ARNP", 
                        "Dr. Andy Nguyen", 
                        "Dr. Syed Abbas", 
                        "Unknown", 
                        "Dr. Fizzah Ali", 
                        "Dr. Viorel Angheloiu", 
                        "Dr. Jennifer Aquino", 
                        "Dr. Amir Aref", 
                        "Dr. Berhane Asfaw", 
                        "Dr. Khalid Aslam", 
                        "Dr. Joseph Barthelemy", 
                        "Dr. Ramon Basa", 
                        "Dr. Kimberly Bell", 
                        "Sharon Bennett, PA-C", 
                        "Dr. Bhavana Bhanot", 
                        "Dr. Himanshu Bhutani", 
                        "Hana Cha, PA-C", 
                        "Dr. Jinsoo Chang", 
                        "Unknown", 
                        "Dr. Sriranjini Chilkunda Ramaswamy", 
                        "Dr. Ishmael Ching", 
                        "Georgia Coote, ARNP", 
                        "Chelsea Crosby, PA-C", 
                        "Dr. Marco Cruz", 
                        "Randal Cupp, PA-C", 
                        "Dr. Lakshmi Datla", 
                        "Dr. Amit Desai", 
                        "Dr. Harjeet Dhillon", 
                        "Dr. Vladimir Dzhashi", 
                        "Dr. Guoping Feng", 
                        "William Finnerty, ARNP", 
                        "Dr. Radu Florea", 
                        "Philip Furth, PA-C", 
                        "Dr. Michal Galeziok", 
                        "Dr. Emad Girgis", 
                        "Dr. Anjna Grover", 
                        "Dr. Matthew Guindon", 
                        "Mary Harris-Tucker, PA-C", 
                        "Mary Harvey, ARNP", 
                        "Dr. Edward Himes", 
                        "Dr. Mai Vi Hoang", 
                        "Unknown", 
                        "Dr. Ihab Ibrahim", 
                        "Dr. Mohamed Imam", 
                        "Lenora Ivanek, PA-C", 
                        "Dr. Nadeem Jaffer", 
                        "Dr. Tonia Jenson", 
                        "Dr. Mark (Jihua) Jia", 
                        "Dr. Audry Kahlstrom", 
                        "Dr. Muhammed Khan", 
                        "Dr. Shadi Khir", 
                        "Unknown", 
                        "Dr. Nikolay Kolev", 
                        "Unknown", 
                        "Dr. Samakshi Krishna", 
                        "Cora Krouse, PA-C", 
                        "Dr. Lakeysha Layfield", 
                        "Dr. David Lee", 
                        "Dr. Desire Lehmann", 
                        "Dr. Michael - PAC L'Italien", 
                        "Dr. Ying Liu", 
                        "Dr. Ed Lopez", 
                        "Laura Luu, ARNP", 
                        "Andrea Lyon-Loftus, PA-C", 
                        "Dr. Naushaba Marri", 
                        "Dr. Liana Maxa", 
                        "Matthew Metsker, PA-C", 
                        "Mihee Montstream, ARNP", 
                        "Albert Morriss, PA-C", 
                        "Unknown", 
                        "Dr. David Munoz", 
                        "Dr. Thankam Nair", 
                        "Michelle Nelson, PA-C", 
                        "Dr. Vivian Nkwonta", 
                        "Dr. Emmy Oh", 
                        "Dr. Srivatsan Padmanabhan", 
                        "Unknown", 
                        "Dr. Ankit Patel", 
                        "Dr. Jay Patel", 
                        "Dr. Seetharam Pothi Reddy", 
                        "Dr. Jeffrey Reasol", 
                        "Dr. Gari Reddy", 
                        "Dr. Prathima Reddy", 
                        "Dr. Azra Rehman", 
                        "Luke Requa, PA-C", 
                        "Dr. David Rochelin", 
                        "Dr. Nirmalya Roychowdhury", 
                        "Dr. Evelyn Rubin", 
                        "Dr. Yasser Said", 
                        "Dr. Vincent Salvador", 
                        "Dr. Shelly Sanetti", 
                        "Dr. Maggie Sekeramayi", 
                        "Dr. Dipam Shah", 
                        "Dr. Megha Shah", 
                        "Dr. Ashwin Shivakumar", 
                        "Dr. Sherrod Shiveley", 
                        "Unknown", 
                        "Dr. Arthur Siek", 
                        "Dr. John Stam", 
                        "Dr. Jessica Tam", 
                        "Dr. Bob Thong", 
                        "Dr. Arinder Tiwana", 
                        "Dr. Tamas Ungar", 
                        "Dr. Nicolas Veohongs", 
                        "Unknown", 
                        "Dr. Pragathy Vutla", 
                        "Dr. John Wagoner", 
                        "Dr. Danhua Wallace", 
                        "Dr. Alison Wright", 
                        "Dr. Gayatri Yambem", 
                        "Dr. Nathaniel Yu Chua", 
                        "Dr. Vitaliy Zak", 
                        "Dr. Wen Zhong", 
                        "Dr. Irina Case", 
                        "Dr. Kelly Carlisle", 
                        "Dr. Mohamed Elagnaf", 
                        "Dr. Zachary Kane", 
                        "Dr. Omar Naji", 
                        "Dr. Phillip Nielson", 
                        "Dr. Rakshit Patnana", 
                        "Dr. Michelle Pham", 
                        "Dr. Jason Chung", 
                        "Dr. Amar Khunti", 
                        "Dr. Sungmi Lian", 
                        "Dr. Dolkar Sherpa", 
                        "Dr. Maninderjit Singh", 
                        "Dr. Chris Stadtherr", 
                        "Dr. Rana Tan", 
                        "Dr. Roberta Trandev", 
                        "Dr. Prabin Uprety", 
                        "Dr. Ashley Hamilton", 
                        "Dr. Timothy Jenkins", 
                        "Dr. Priyanka Kapoor", 
                        "Dr. Ali Alhusseni", 
                        "Dr. Pushpanjali Basnyat", 
                        "Dr. Megha Bendre", 
                        "Dr. Shaluk Biswas", 
                        "Dr. Judy Emil Dela Cruz", 
                        "Dr. Dhananjay Deo", 
                        "Dr. Tianhai (Tim) Guo", 
                        "Dr. Dana Ionescu", 
                        "Dr. Priya Kanwar", 
                        "Dr. Kelly Liu", 
                        "Janet MacKay, RN", 
                        "Dr. Aimee Shariat", 
                        "Dr. Maryam Tariq", 
                        "Kelly Taylor", 
                        "Dr. Thomson Tuscano", 
                        "Dr. Dong Vo"
                    ]
                }
            }, 
            "Neurosurgery": {
                "selectOptions": {
                    "conditions": [
                        "Not applicable", 
                        "Acute blood loss anemia", 
                        "Hyponatremia", 
                        "Hypernatremia", 
                        "Chronic kidney disease stage 3", 
                        "Chronic kidney disease stage 4", 
                        "Chronic kidney disease stage 5", 
                        "Encephalopathy due to [specific cause]", 
                        "Acute respiratory failure [with hypoxia and/or hypercapnia]", 
                        "Acute kidney injury", 
                        "Cerebral edema", 
                        "Coma GCS score time of record", 
                        "Compression of brain", 
                        "Drug dependence continuous use", 
                        "Hemiparesis [side dominance]", 
                        "Hemiplegia [side dominance]", 
                        "Myelopathy [vascular or nonvascular]"
                    ], 
                    "hospitals": [
                        "Harrison", 
                        "Highline", 
                        "St. Anthony", 
                        "St. Clare", 
                        "St. Elizabeth", 
                        "St. Francis", 
                        "St. Joseph"
                    ], 
                    "providers": [
                        "Kelly Andersson, PA-C", 
                        "Dr. Marc Goldman", 
                        "Yelena Golub, PA-C", 
                        "Vladimir V. Grib, ARNP", 
                        "Anastasia Heins, PA-C", 
                        "Caoilin Hoctor, PA-C", 
                        "Catherine Ignacio, ARNP", 
                        "Steven Johns, PA-C", 
                        "Dr. Alex Mohit", 
                        "Dr. Daniel Nehls", 
                        "Dr. Michael Schlitt", 
                        "Dr. Hoan Tran"
                    ]
                }
            }, 
            "Vascular": {
                "selectOptions": {
                    "conditions": [
                        "Not applicable", 
                        "Acute blood loss anemia", 
                        "Acute diastolic heart failure", 
                        "Chronic diastolic heart failure", 
                        "Acute systolic heart failure", 
                        "Chronic systolic heart failure", 
                        "Hyponatremia", 
                        "Hypernatremia", 
                        "Chronic kidney disease stage 3", 
                        "Chronic kidney disease stage 4", 
                        "Chronic kidney disease stage 5", 
                        "Encephalopathy due to [specific cause]", 
                        "Morbid obesity exact BMI", 
                        "Severe protein-calorie malnutrition exact BMI", 
                        "Septic shock", 
                        "Acute respiratory failure [with hypoxia and/or hypercapnia]", 
                        "Drug dependence continuous use"
                    ], 
                    "hospitals": [
                        "Harrison", 
                        "Highline", 
                        "St. Anthony", 
                        "St. Clare", 
                        "St. Elizabeth", 
                        "St. Francis", 
                        "St. Joseph"
                    ], 
                    "providers": [
                        "Jennifer Barnett, ARNP", 
                        "Pamela Charboneau, ARNP", 
                        "Alexandra Engstrom, PA-C", 
                        "Elaine Kiser-Rude, PA-C.", 
                        "Jennifer Moore, PA-C", 
                        "Rachel Sammis-Falk, PA-C", 
                        "Teri Scott, ARNP", 
                        "Anna Singur, PA-C", 
                        "Shawn Tedford, PA-C"
                    ]
                }
            }
        }
    }, 
    "Piedmont": {
        "diagnosisCategorySelectOptions": [
            "Accurately Captured", 
            "Misdiagnosed", 
            "Omitted"
        ], 
        "groups": {
            "Cardiology": {
                "selectOptions": {
                    "conditions": [
                        "Acute blood loss anemia", 
                        "Acute heart failure with reduced EF (HFrEF)\n ", 
                        "Acute heart failure with preserved EF (HFpEF)", 
                        "Acute kidney injury ", 
                        "Acute myocardial infarction [specify type, location, and designation of initial/ subsequent/old]", 
                        "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Cardiac arrhythmia [specify type]", 
                        "Chronic heart failure\u00a0with reduced EF (HFrEF)", 
                        "Chronic heart failure with preserved EF (HFpEF)", 
                        "Chronic kidney disease [stage 3, 4, 5, or ESRD, on dialysis]", 
                        "Encephalopathy due to [specify cause]", 
                        "Hypernatremia", 
                        "Hyponatremia", 
                        "Morbid obesity [BMI]", 
                        "Pleural effusion", 
                        "Sepsis", 
                        "Septic shock", 
                        "Severe sepsis", 
                        "Venous thromboembolism [specify DVT or PE, acute or chronic]"
                    ], 
                    "hospitals": [
                        "Piedmont Atlanta", 
                        "Piedmont Henry", 
                        "Piedmont Mountainside"
                    ], 
                    "providers": [
                        "Stephanie Aaron, NP", 
                        "Nicole Adams, PA", 
                        "Leslie Adcock, NP", 
                        "Leah Alford-Scharff, NP", 
                        "Kabir Ali, PA-C", 
                        "Harriett Allen, NP", 
                        "Christine Armstrong, NP", 
                        "Dr. William Stanley Arnold", 
                        "Amy Aspinwall, PA", 
                        "Chelsea Baer, PA", 
                        "Dr. William (Chuck) Ballard", 
                        "Hannah Barnes", 
                        "Dr. Peter Barratt", 
                        "Dr. Louis L. Battey", 
                        "Dr. Patrick M Battey", 
                        "Dr. Ashish Ambavi Bhimani", 
                        "Ashley Blackmon, NP", 
                        "Dr. Raul Blanco", 
                        "Dr. Brian Bledsoe", 
                        "Dr. William A. Blincoe", 
                        "Lara Bradbury, NP", 
                        "Meredith Brazell, PA-C", 
                        "Dr. Charles L. Brown III", 
                        "Dr. William Morris Brown III", 
                        "Dr. Jaime Burkle", 
                        "Blynnsa Call, NP", 
                        "Dr. Adam Carlisle", 
                        "Dr. Harold Carlson", 
                        "Andrew Caruso, PA", 
                        "Dr. Veer Chahwala", 
                        "Susan Clymer, NP", 
                        "Matt Cocchiola, PA-C", 
                        "Dr. Mark L. Cohen", 
                        "Dr. Arthur J. Cook Jr.", 
                        "Dr. Victor E. Corrigan", 
                        "Brittany D'Amici, PA-C", 
                        "Dr. Jack E. Dawson", 
                        "Dr. David Dean", 
                        "Lynn Dean, NP", 
                        "Dr. Thomas F. Deering", 
                        "Christina Delgaudio, PA", 
                        "Michael Doyle, PA", 
                        "Kelleen Duncan, NP", 
                        "Sandy Duncan, NP", 
                        "Dr. Edward Dykman", 
                        "Alisa Erridge, PA-C", 
                        "Dr. Ben-Arie Eyal", 
                        "Virginia Ezenne, NP", 
                        "Alena Favorov, NP", 
                        "Dr. Peter Flueckiger", 
                        "Charles Foreman", 
                        "Dave Foreman, PA-C", 
                        "Anna Forman, NP", 
                        "Kiernan Garfinkel, NP", 
                        "Dr. John, Parker Gott", 
                        "Dr. Sandeep Kumar Goyal", 
                        "Jeffrey Greene, PA", 
                        "Dr. David Grenda", 
                        "Meghan Grone, NP", 
                        "Cherille Hamilton, NP", 
                        "Bibi Haniff, PA", 
                        "Alexandra Hodson, PA", 
                        "Delaina Hooks, PA-C", 
                        "Dr. Tara Hrobrowski", 
                        "Yuan Hu, NP", 
                        "Kathryn Hughes, NP", 
                        "Megan Hull, NP", 
                        "Cletus Ibe", 
                        "Russell James, NP", 
                        "Lindsay Johnson, NP", 
                        "Susan Johnston, NP", 
                        "Nikisha Jones, NP", 
                        "Dr. Ashish Kabra", 
                        "Dr. Anna M. Kalynych", 
                        "Dr. David E. Kandzari", 
                        "Dr. Sricharan C. Kantipudi", 
                        "Danielle Kaplan, PA", 
                        "Dr. Prashant Kaul", 
                        "Dr. James Kauten", 
                        "Dr. Saied Khansarinia", 
                        "Jamison King, PA", 
                        "Meghan Kirkland, PA", 
                        "Dr. Andrew John Klein", 
                        "Dr. Arun Krishnamoorthy", 
                        "Jenina Lagasca, NP", 
                        "Dr. Sanjay M. Lall", 
                        "Jeffrey Lefeber, PA", 
                        "Julie Locke, PA", 
                        "Jason Lucas, PA-C", 
                        "Ken Lyda, NP", 
                        "Dr. Shailesh Malla", 
                        "Dr. Walter E. Mashman", 
                        "Laura Mayover, NP", 
                        "Dr. Christopher Meduri", 
                        "Dr. Federico Milla", 
                        "Phillip Miller", 
                        "Dr. Joseph I. Miller III", 
                        "Dr. Joseph I. Miller Jr", 
                        "Anne Mishkofski, PA", 
                        "Dr. Sara Mobasseri", 
                        "Nicole Moore, NP", 
                        "Wesley Moore", 
                        "Mitra Moshksaran, NP", 
                        "Rose Musille, PA", 
                        "Kimberly Williams Naab, PA-C", 
                        "Lien Nguyen, PA-C", 
                        "Ashraf Panjwani, NP", 
                        "David Patrick, NP", 
                        "Andrea Perez, NP", 
                        "Caroline Pierce, NP", 
                        "Dr. Venkateshwar Polsani", 
                        "Erin Porter, NP", 
                        "Dr. Robert Powers", 
                        "Dr. Vivek Rajagopal", 
                        "Kanniammal Ramaswamy, NP", 
                        "Kristyn Ramsey, PA-C", 
                        "Katie Rattray, NP", 
                        "Micaline Regis, PA-C", 
                        "Maureen Reis, NP", 
                        "Dr. Sarah J. Rinehart", 
                        "Kristen Robbins, NP", 
                        "Dr. Charles Ross", 
                        "Dr. Hassan S. Sayegh", 
                        "Dr. Eric Sceusi", 
                        "Dr. Jyoti Sharma", 
                        "Jay Shray, PA", 
                        "Dr. Steven R. Sigman", 
                        "Eddie Simms, PA ", 
                        "Dr. Lawrence E. Simpson III", 
                        "Cherie Smith, NP", 
                        "Dr. Bobby Smith", 
                        "Kristin Sparks, NP", 
                        "Richard St. Charles", 
                        "Dr. Bruce Stambler", 
                        "Jennifer Strother, NP", 
                        "Kristin Szurovy, PA", 
                        "Caroline Taylor, PA", 
                        "Dr. Kenneth Taylor", 
                        "Cherise Thomas, PA-C", 
                        "Dr. Brian Thomas", 
                        "Diana Throckmorton, NP", 
                        "Dr. David Tian", 
                        "Scott Turner, PA-C", 
                        "Dr. Andrew W. Unzeitig", 
                        "Dr. Mani Vannan", 
                        "Julia Varghese, NP", 
                        "Dr. Africa Wallace", 
                        "Christopher Walsh, PA", 
                        "Lindsay Watters, PA", 
                        "Michael Watts, NP", 
                        "Amynah Welji, PA", 
                        "Adrianne West, NP", 
                        "Sarah White", 
                        "Dr. Andrew C. Wickliffe", 
                        "Angela Wilder, NP", 
                        "Olive Williams, NP", 
                        "Dr. Charles I. Wilmer", 
                        "Stacey Wilson, NP", 
                        "Deirdre Zimmerman, PA", 
                        "Dr. Chituru Adele", 
                        "Dr. Homayoun Sadreddin Amin", 
                        "Andrea Nicole Bernard, NP", 
                        "Dr. Meryl Lynn Braunstein", 
                        "Macy Cook, PA", 
                        "Dr. Jarrod Day", 
                        "Dr. Abdulrahman Doughan", 
                        "Dr. Patrick A. Egbe", 
                        "Amanda Lauren Farrell, NP", 
                        "Dr. Akshay Gupta", 
                        "Teresa Hollowell, NP", 
                        "Dr. Jeevith Reddy Kanukunta", 
                        "Elizabeth Matheny, PA", 
                        "Dr. Kenneth Fredrick Menchion", 
                        "Dr. Camille Debra Nelson", 
                        "Dr. Gregory Paul Petro", 
                        "Dr. Pritam Rao Polkampally", 
                        "Dr. Gopal C. Rao", 
                        "Dr. Rajasekhar Reddy", 
                        "Dr. Michael Roberds Rutledge", 
                        "Dr. Muthusamy Sekar ", 
                        "Robert Sikes, PA-C", 
                        "Dr. John Darrell Smith", 
                        "Jennifer Christie Waite, NP", 
                        "Dr. Jimmie Dale Cannon Jr.", 
                        "Dr. Roberto F. Pereira", 
                        "Sara Williams, NP"
                    ]
                }
            }, 
            "Hospitalist": {
                "selectOptions": {
                    "conditions": [
                        "Acute blood loss anemia", 
                        "Acute heart failure with reduced EF (HFrEF)\n ", 
                        "Acute heart failure with preserved EF (HFpEF)", 
                        "Acute kidney injury", 
                        "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Chronic heart failure\u00a0with reduced EF (HFrEF)", 
                        "Chronic heart failure with preserved EF (HFpEF)", 
                        "Chronic kidney disease [stage 3, 4, 5, or ESRD, on dialysis]", 
                        "Drug [type] dependence [active or in remission]", 
                        "Encephalopathy due to [specify cause]", 
                        "Hypernatremia", 
                        "Hyponatremia", 
                        "Morbid obesity [BMI]", 
                        "Sepsis", 
                        "Septic shock", 
                        "Severe sepsis", 
                        "Shock [specify type or cause]", 
                        "Status conditions"
                    ], 
                    "hospitals": [
                        "Piedmont Atlanta", 
                        "Piedmont Henry", 
                        "Piedmont Mountainside"
                    ], 
                    "providers": [
                        "Dr. Atishi Aggarwal", 
                        "Dr. Hodan Ahmed", 
                        "Dr. Marie-Veronique Bielo", 
                        "Dr. Amber Boyd", 
                        "Dr. Nana Britwum", 
                        "Nina Dardy, NP", 
                        "Aruna Diptee, NP", 
                        "Dr. Jason Douglas", 
                        "Dr. Efe Efemini", 
                        "Dr. Munit Emlaelu", 
                        "Dr. Sefanit Gebretsadik", 
                        "Dr. Helen Gidey", 
                        "Dr. Smriti Goyal", 
                        "Dr. Nesrudin Hamid", 
                        "Dr. Mesha Harris", 
                        "Lorena Hendry, PA", 
                        "Dr. Ray Hinton", 
                        "Destiny Howe, NP", 
                        "Dr. Andy Jaffal", 
                        "Shang Jones, NP", 
                        "Dr. Pramod Kakarala", 
                        "Dr. Emilio Lacayo", 
                        "Dr. Cheri Lamb", 
                        "Dr. Laurentia (Laura) Lascar", 
                        "Dr. Mihai (Mike) Lascar", 
                        "Larry Lassiter, NP", 
                        "Frances Lockwood, PA-C", 
                        "Nina Loftus, NP", 
                        "Dr. Bharani Oggu", 
                        "Dr. Nnaemeka Okaro", 
                        "Dr. Jalil Omar", 
                        "Sarah Omodele", 
                        "Dr. Pritesh Patel", 
                        "Shalonda Pettis, PA-C", 
                        "Lisa Piper, PA", 
                        "William Rice", 
                        "Alfred Rodriguez, PA", 
                        "Dr. Bhumik Shah", 
                        "Dr. Zeeba Siddiqi", 
                        "Amy Simone, PA-C", 
                        "Dr. Emeka Uwakwe", 
                        "Dr. Ulma Vedala", 
                        "Ashley Waldrop, PA-C", 
                        "Dr. Darin Wilson", 
                        "Christianah Adekoya, NP", 
                        "Dr. Zuhair Ahmed", 
                        "Dr. Ifeoma Amobi", 
                        "Dr. Eva Isabelle Beaulieu", 
                        "Dr. Charles Bradford", 
                        "Dr. Rita Claxton", 
                        "Olivia Croxton, PA-C", 
                        "Dr. Christopher Dalinkus", 
                        "Bijal Desai, PA", 
                        "Dr. Brendan Doucette", 
                        "Dr. Ivorie Drayton", 
                        "Dr. Greg Evans", 
                        "Dr. Noble Iwuagwu", 
                        "Alexcia James, NP", 
                        "Dr. Gregory Jones", 
                        "Dr. Diana Lee", 
                        "Dr. Emily Mason", 
                        "Simone Mccray, NP", 
                        "Dr. Marc Neeland", 
                        "Millicent Ogoo, NP", 
                        "Dr. Omokayode Omotoso", 
                        "Dr. Maxcene Oreus", 
                        "Dr. Alpesh Patel", 
                        "Dr. Jaymin Patel", 
                        "Dr. Sandeep Patel", 
                        "Dr. Ramesh Reddy", 
                        "Dr. Mobin Shah", 
                        "Dr. Eze Ugwueze", 
                        "Dr. Willie Winzer", 
                        "Dr. Crystal Ann Comeau", 
                        "Jason Fleury, PA", 
                        "Devra Kiewit, NP", 
                        "Dr. Ingle Brandan Owens-Schnars", 
                        "Michelle Queen, NP", 
                        "Dr. Katherine Elizabeth Stein", 
                        "Dr. Jesus Gustavo Vazquez-Figueroa"
                    ]
                }
            }, 
            "Neurosurgery": {
                "selectOptions": {
                    "conditions": [
                        "Acute blood loss anemia", 
                        "Acute kidney injury", 
                        "Acute respiratory failure [with hypoxia and/or hypercapnia]", 
                        "Cerebral edema", 
                        "Chronic kidney disease \nStage 3, 4, or 5", 
                        "Coma, GCS score, time of record", 
                        "Compression of brain", 
                        "Drug dependence, continuous use", 
                        "Encephalopathy due to [specific cause]", 
                        "Hemiparesis [side, dominance]", 
                        "Hemiplegia [side, dominance]", 
                        "Hypernatremia", 
                        "Hyponatremia", 
                        "Myelopathy [vascular or nonvascular]"
                    ], 
                    "hospitals": [
                        "Piedmont Atlanta"
                    ], 
                    "providers": [
                        "Dr. David Benglis", 
                        "Patrice Braun, NP", 
                        "Dr. Howard Chandler", 
                        "Dr. Roger Frankel", 
                        "Dr. Gary Gropper", 
                        "Dr. Regis Haid", 
                        "Dr. Michele Johnson", 
                        "Joseph Lamb, PA-C", 
                        "Dr. David McCracken", 
                        "Nancy Olansen, PA-C", 
                        "Laura Prado, NP", 
                        "Danielle Underwood, NP", 
                        "Melissa Voyles, PA", 
                        "Dr. Steven Wray", 
                        "Jane Yoffe, NP"
                    ]
                }
            }, 
            "Pulmonology": {
                "selectOptions": {
                    "conditions": [
                        "Acute heart failure with reduced EF (HFrEF)\n ", 
                        "Acute heart failure with preserved EF (HFpEF)", 
                        "Acute Kidney Injury (CC) ", 
                        "Acute respiratory failure [specify with hypoxia and/or hypercapnia]", 
                        "Chronic heart failure\u00a0 with reduced EF (HFrEF)", 
                        "Chronic heart failure with preserved EF (HFpEF)", 
                        "Chronic kidney disease [stage 3, 4, 5, or ESRD, on dialysis]", 
                        "Chronic respiratory failure with hypoxia and/or hypercapnia", 
                        "Encephalopathy due to [specify cause]", 
                        "Hypernatremia", 
                        "Hyponatremia", 
                        "Morbid obesity [BMI]", 
                        "Pleural Effusion", 
                        "Pneumothorax", 
                        "Sepsis", 
                        "Septic shock", 
                        "Severe sepsis", 
                        "Pneumonia [specify type/cause, and if present on admission (POA)]", 
                        "Venous Thromboembolism [Specify Dvt Or Pe, Acute Or Chronic]"
                    ], 
                    "hospitals": [
                        "Piedmont Atlanta", 
                        "Piedmont Henry", 
                        "Piedmont Mountainside"
                    ], 
                    "providers": [
                        "Elisabeth Adele", 
                        "Jeremy Amayo, PA-C", 
                        "Sandeep Anand, PA-C", 
                        "Jordan Bicher, PA-C", 
                        "Antuane Boston, PA", 
                        "Luisa Bowzard, PA", 
                        "Michael Burton, PA", 
                        "Dr. Ryan Carrick", 
                        "Dr. Amy Case", 
                        "Dr. Chad Case", 
                        "Dr. James Chang", 
                        "Gina Cochran, PA", 
                        "Sarah Craven, PA-C", 
                        "Ashley Gantt, PA", 
                        "Dr. Alexander Gluzman", 
                        "Michelle Gorzelnik, PA", 
                        "Dr. Steven Harris", 
                        "Dr. Charles Hartley", 
                        "John Heisler, PA", 
                        "Grace Higgins, PA-C", 
                        "Dr. Aris Iatridis", 
                        "Michelle Irwin, NP", 
                        "Dr. Jermaine Jackson", 
                        "Paige Johnson, PA", 
                        "Dr. William Kenny", 
                        "Dr. Charles Lassiter", 
                        "Dr. Brion Lock", 
                        "Carole Lovering, NP", 
                        "Dr. Ralitza Martin", 
                        "Dr. Chad Miller", 
                        "Stacy Mossberger, PA", 
                        "Dr. Susan Mucha", 
                        "Leslie Narain, PA-C", 
                        "Yodit Oliver, NP", 
                        "Dr. Ram Paramesh", 
                        "Dr. Craig Patterson", 
                        "Bethany Quinn, PA-C", 
                        "Kelly Raines, PA-C", 
                        "Lori Reed, NP", 
                        "Dr. Brett Sandifer", 
                        "Dr. Matt Schmit", 
                        "Dr. Cliff Settle", 
                        "Jessica Shelnutt, PA", 
                        "Dr. Stuart Simon", 
                        "Dr. Samuel Szumstein", 
                        "James Torell, PA", 
                        "Colleen Vadia, PA", 
                        "Christy Wilson, NP", 
                        "Dr. Paul Zolty", 
                        "Dr. Robert Budman", 
                        "Kathryn Berman, PA", 
                        "Brittany Bowman, PA-C", 
                        "Dr. Jennifer Butler", 
                        "Dr. Khush Chokshi", 
                        "Nicholas Colavito, PA-C", 
                        "Clay Ditty, NP", 
                        "Kevin Glenn, PA", 
                        "Dr. Ogbanna Ogbu", 
                        "Nathan Potter, PA", 
                        "William Rutland, PA-C", 
                        "Dr. Tamim Mohamad Al-Kharrat"
                    ]
                }
            }
        }
    }
}